### ISSUE TITLE
.NET Client

### ISSUE THREAD

**Issue by hrkeni** [elastic/enterprise-search-ruby#128]
Hello! I apologize if this is not the right spot for this but I didn't know where to go. My team is very interested in utilizing app search and we are a .NET shop. Are there any plans to get a .NET client for enterprise search? I would be happy to contribute a little bit of my time to one.

**Comment by philkra** [comment]
@hrkeni thank you for reaching out. Yes, absolutely we plan to create an Enterprise Search .NET client, but we don't have an ETA for it yet. It's exciting to hear your interest in contributing, as soon as we have something to show, I'll ping on this ticket.
