### ISSUE TITLE
Missing engine authentication endpoint

### ISSUE THREAD

**Issue by lengoyvaerts** [elastic/enterprise-search-ruby#129]
It seems like the engine authentication endpoint, as described [here](https://www.elastic.co/guide/en/app-search/current/engines.html#engines-authentication), is currently missing.

I believe adding this endpoint could fix an [issue](https://github.com/logstash-plugins/logstash-output-elastic_app_search/issues/22) concerning the Logstash App Search output plugin, which I'm currently experiencing.

**Comment by sethmlarson** [comment]
Might this be the `list_engines` API?

**Comment by lengoyvaerts** [comment]
Indeed, it seems like it's the same endpoint.

As for the issue, it's probably another team that manages this. Does the proposed change sound meaningful?

**Comment by sethmlarson** [comment]
@lengoyvaerts You're right that another team manages the repo you linked to. I think that the Logstash plugin you're linking to uses the previous `elastic-app-search` package, that package is deprecated in favor of this new package `elastic-enterprise-search`. Would be a good idea to move over to the new package, the migration itself shouldn't be too painful as I believe the APIs are similar.

**Comment by lengoyvaerts** [comment]
@sethmlarson Thanks for the info. 
I can't seem to find any record of this deprecation or find this `elastic-enterprise-search` in the Logstash Plugins repo or the Logstash documentation. Could you point me in the right direction please?

**Comment by sethmlarson** [comment]
Sorry for the confusion:

- [`elastic-enterprise-search` package](https://rubygems.org/gems/elastic-enterprise-search) source code is in this current repository, [`elastic/enterprise-search-ruby`](https://github.com/elastic/enterprise-search-ruby).
- [`elastic-app-search` package](https://rubygems.org/gems/elastic-app-search) source code is in [`elastic/app-search-ruby`](https://github.com/elastic/app-search-ruby) which has been deprecated (see the README).
- The Logstash plugin you linked to uses `elastic-app-search` but likely should be updated to use `elastic-enterprise-search`

Does this make things clearer?

**Comment by lengoyvaerts** [comment]
Thanks for the clarification. 

Do you have any insight you could share on when the Logstash plugin will get updated to use this new package? And can updates like this happen between releases or do they typically wait until a new Elastic stack release?

**Comment by sethmlarson** [comment]
I've [created an issue](https://github.com/logstash-plugins/logstash-output-elastic_app_search/issues/23) on the repo to track the update. I'll ping an internal team on this issue, unsure when it'll be done+released but likely won't need to wait for an Elastic Stack release just based on the versioning scheme.

I'm closing this issue in favor of the other opened issues on that repository. Thank you for reporting!

**Comment by sethmlarson** [comment]
Also if you're willing to make a contribution fixing the issue, that'd be super appreciated I'm sure ;)

**Comment by lengoyvaerts** [comment]
Thanks @sethmlarson 
I'll see what I can do!
