### ISSUE TITLE
 already initialized constant Elastic::META_HEADER_SERVICE_VERSION when using elasticsearch gem and this gem in the same app

### ISSUE THREAD

**Issue by weilandia** [elastic/enterprise-search-ruby#145]
Assignment is here: https://github.com/elastic/enterprise-search-ruby/blob/a8b410ad1c8979da08020c62b64f405b60c0f9db/lib/elastic/enterprise-search/client.rb#L34

**Comment by weilandia** [comment]
Might be best just to remove this line: https://github.com/elastic/elasticsearch-ruby/blob/1dc5d322310aad4ced6975ed914d5b64c244187b/elasticsearch/lib/elasticsearch.rb#L40

Since it will happen by default here: https://github.com/elastic/elasticsearch-ruby/blob/1dc5d322310aad4ced6975ed914d5b64c244187b/elasticsearch-transport/lib/elasticsearch/transport/meta_header.rb#L44

But this way all the meta info will look like it's coming from `:ent` even if it is not

**Comment by picandocodigo** [comment]
@weilandia thanks for reporting this! I hadn't tested the possibility of using both clients.

I think a better approach to address this will be to not have `Elastic::META_HEADER_SERVICE_VERSION` defined on each client and use something more specific. I'll address this and release a fix as soon as possible and I'll let you know!

**Comment by picandocodigo** [comment]
Hi @weilandi,
I've just released `v7.13.0.pre` of both the `elasticsearch` and `elastic-enterprise-search` gems. They should fix the warning, so feel free to test them for your project, or you can wait for the final versions of 7.13.0 which will release with the rest of the stack.
