### ISSUE TITLE
`elasticsearch-transport` version

### ISSUE THREAD

**Issue by wentaoxu415** [elastic/enterprise-search-ruby#235]
For the latest v7.x versions, (v7.13~7.16) the Gemspec file is specifying `elasticsearch-transport` version as `'~> 7.13.0'` 
https://github.com/elastic/enterprise-search-ruby/blob/7.16/elastic-enterprise-search.gemspec#L50

I was wondering if the minor version of the `elasticsearch-transport` should have been going up alongside the increase in the minor version of `enterprise-search-ruby`. 

Otherwise, this creates an issue where attempt to install both `elasticsearch-ruby` and `enterprise-search-ruby` runs into the following dependency conflict for `elasticsearch-transport`

```Bundler could not find compatible versions for gem "elasticsearch-transport":
  In Gemfile:
    elastic-enterprise-search (= 7.14.0) was resolved to 7.14.0, which depends on
      elasticsearch-transport (~> 7.13.0)

    elasticsearch (= 7.14.1) was resolved to 7.14.1, which depends on
      elasticsearch-transport (= 7.14.1)

**Comment by picandocodigo** [comment]
Hi @wentaoxu415, thanks for reporting this! This was an oversight on my part. I'm updating the code to allow for a more open dependency on `elasticsearch-transport`. I'm going to backport this to the latest `7.x` releases and publish `.1` versions with the fix.

**Comment by picandocodigo** [comment]
Versions [`7.14.1`](https://github.com/elastic/enterprise-search-ruby/releases/tag/v7.14.1) and [`7.15.1`](https://github.com/elastic/enterprise-search-ruby/releases/tag/v7.15.1) are out with the fix :+1:

**Comment by wentaoxu415** [comment]
Thanks for this quick fix @picandocodigo!
