### ISSUE TITLE
Expose transport client's adapter parameter and document how using different adapters affects performance

### ISSUE THREAD

**Issue by kovyrin** [elastic/enterprise-search-ruby#252]
I've done an investigation recently trying out every Enterprise Search API clients and making sure they all used persistent HTTP connections whenever possible to reduce the impact of TCP and SSL handshakes on API requests to Elastic Cloud instances. While doing so, I have noticed, that there is no way to tell the Enterprise Search client to use a specific adapter and it is not immediately obvious what adapters are supported and how they impact performance. 

As a result of this ambiguity, a simple ruby script that performs a 100 requests to an Elastic Cloud cluster takes 3.5 times longer that it has to since the default adapter does not support persistent connections.

I think it would be very useful to directly call out the existence of different adapters in the underlying transport client and explain how not using a proper adapter is going to extremely detrimental to any production use of the API client.

Additionally, allowing users to pass the `:adapter` argument to the client would make it much easier to control what adapters are used (passing it through to the underlying transport client). Without it, users have to manually construct a transport object and pass it to the API, which is a bit awkward IMO.

**Comment by picandocodigo** [comment]
Thanks for this @kovyrin. I'm going to add an easier way to choose an adapter and once that's implemented, add more information in the docs to warn users about the impact of using HTTP libraries which support persistent HTTP connections :+1:

**Comment by picandocodigo** [comment]
@kovyrin if there is such a big difference, before the release of `8.0`, we could add one of the libraries which support persisten HTTP connections as a dependency and make it the default adapter for a better user experience. What do you think?

**Comment by kovyrin** [comment]
> @kovyrin if there is such a big difference, before the release of `8.0`, we could add one of the libraries which support persisten HTTP connections as a dependency and make it the default adapter for a better user experience. What do you think?

The problem with requiring a specific adapter as a dependency is that in many cases it'd clash with the HTTP clients people have already included in their project and could lead to all kinds of weird environment issues. I'd err on the side of caution here and try to document it as prominently as possible without forcing people to adopt a specific client here.
