### ISSUE TITLE
Faraday::ConnectionFailed (execution expired)

### ISSUE THREAD

**Issue by lauramosher** [elastic/enterprise-search-ruby#61]
Found my way to this repository per the Deprecation warning in https://github.com/elastic/app-search-ruby

## Issue

receiving Faraday::ConnectionFailed error whenever I try to run API calls through this Gem.

## Steps I took

I tried both standalone and through Enterprise search client setup

```ruby
# didn't work
client = Elastic::EnterpriseSearch::AppSearch::Client.new(host: "https://<id>.ent-search.us-east-1.aws.cloud.es.io", http_auth: "private-api-key")

# also didn't work
ent_client = Elastic::EnterpriseSearch::Client.new(host: "https://<id>.ent-search.us-east-1.aws.cloud.es.io", http_auth: "private-api-key")

# also didn't work
ent_client = Elastic::EnterpriseSearch::Client.new(host: "https://<id>.ent-search.us-east-1.aws.cloud.es.io")
app_client = ent_client.app_search(http_auth: "private-api-key")

# also didn't work
ent_client = Elastic::EnterpriseSearch::Client.new(host: "https://<id>.ent-search.us-east-1.aws.cloud.es.io")
app_client = ent_client.app_search.http_auth = "private-api-key"

# and also didn't work, when I tried to just search against my existing engine
ent_client = Elastic::EnterpriseSearch::Client.new(host: "https://<id>.ent-search.us-east-1.aws.cloud.es.io")
app_client = ent_client.app_search(http_auth: "search-api-key")
```

And I tried:

`client.list_engines`
`client.index_documents`
`client.version`

and all received a connection failed error.

I also verified that my app client http_auth returned my API key, `app_client.http_auth`, which it did.

For now, I'm planning on going back to the other Gem which does appear to work for me. Let me know if there is anything else you'd like me to try!

**Comment by picandocodigo** [comment]
Hi @lauramoshe, thanks for reporting this!
I just came back from annual leave so I'm seeing this issue just now. I'll look into this as soon as I can and I'll let you know.

Thanks!

**Comment by picandocodigo** [comment]
Hi @lauramosher, there was an issue with `elasticsearch-transport` which has been addressed and fixed in release `7.10.1`.

You should be able to update `elasticsearch-transport` in your project by running `bundle update elasticsearch-transport`. Please let me know if that solves the issue for you. Thank you!

**Comment by lauramosher** [comment]
Hello! Sorry for the delay. I ended up switching back to Elasticsearch, rather than Enterprise Search, for the app I was working on. I'm happy to close this out as resolved regardless.

**Comment by picandocodigo** [comment]
@lauramosher thanks for reporting back, I'll close the issue then :+1:
